// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Palpitao.Api.Data;

#nullable disable

namespace Palpitao.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617190757_AddPredictionSubmissionMode")]
    partial class AddPredictionSubmissionMode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Palpitao.Api.Entities.Absence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AbsenceNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PenaltyPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("RoundId", "UserId")
                        .IsUnique();

                    b.ToTable("Absences");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.AbsenceOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("boolean");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("RoundId", "UserId")
                        .IsUnique();

                    b.ToTable("AbsenceOverrides");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb");

                    b.Property<string>("EntityId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowParticipantsToSubmitPredictions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowParticipantsToViewOthersPredictions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("TournamentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("PalpitaoEngland");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            AllowParticipantsToSubmitPredictions = true,
                            AllowParticipantsToViewOthersPredictions = false,
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Description = "Bolão da temporada inglesa.",
                            IsActive = true,
                            Name = "Palpitão England 2025/2026",
                            OwnerUserId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Slug = "palpitao-england-2025-2026",
                            TournamentType = "PalpitaoEngland",
                            UpdatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Palpitao.Api.Entities.GroupUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEliminated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RejectedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupId", "Status");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique();

                    b.ToTable("GroupUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            ApprovedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GroupId = new Guid("33333333-3333-3333-3333-333333333301"),
                            IsActive = true,
                            IsEliminated = false,
                            Role = "GroupAdmin",
                            Status = "Approved",
                            UpdatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("22222222-2222-2222-2222-222222222201")
                        });
                });

            modelBuilder.Entity("Palpitao.Api.Entities.OcrImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text");

                    b.Property<string>("LanguageUsed")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("StoredFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("OcrImportBatches");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.OcrPredictionCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MatchTextRaw")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("NeedsReview")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OcrImportBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParticipantNameRaw")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PredictedAwayScore")
                        .HasColumnType("integer");

                    b.Property<int?>("PredictedHomeScore")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoundMatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OcrImportBatchId");

                    b.ToTable("OcrPredictionCandidates");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.Prediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("PredictedAwayScore")
                        .HasColumnType("integer");

                    b.Property<int>("PredictedHomeScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoundMatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScoreCategory")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("RoundId", "UserId");

                    b.HasIndex("RoundMatchId", "UserId")
                        .IsUnique();

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.PredictionScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BasePoints")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FinalPoints")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrectColumn")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExactScore")
                        .HasColumnType("boolean");

                    b.Property<int>("Multiplier")
                        .HasColumnType("integer");

                    b.Property<Guid>("PredictionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoundMatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScoreCategory")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("RoundId", "UserId");

                    b.HasIndex("RoundMatchId", "UserId")
                        .IsUnique();

                    b.ToTable("PredictionScores");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FirstMatchStartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FlavioConflictAlert")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FlavioDeadlineUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FlavioRuleApplies")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("FlavioRuleTargetUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("33333333-3333-3333-3333-333333333301"));

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MirrorPublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ResultsUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Title")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("GroupId");

                    b.HasIndex("SeasonId", "Number")
                        .IsUnique();

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.RoundMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Competition")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalMatchId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ExternalMatchUrl")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastResultUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManualMultiplierJustification")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ManualMultiplierOverride")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ResultSource")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("NotStarted");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("RoundId");

                    b.ToTable("RoundMatches");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.RoundParticipantResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FinalPoints")
                        .HasColumnType("integer");

                    b.Property<bool>("FlavioRuleApplied")
                        .HasColumnType("boolean");

                    b.Property<int>("GrossPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("33333333-3333-3333-3333-333333333301"));

                    b.Property<int>("PenaltyPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasAbsent")
                        .HasColumnType("boolean");

                    b.Property<bool>("WasEliminated")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.HasIndex("RoundId", "UserId")
                        .IsUnique();

                    b.HasIndex("SeasonId", "UserId");

                    b.ToTable("RoundParticipantResults");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("33333333-3333-3333-3333-333333333301"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.Standing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AbsenceCount")
                        .HasColumnType("integer");

                    b.Property<int>("ExactCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("33333333-3333-3333-3333-333333333301"));

                    b.Property<int>("PenaltyPoints")
                        .HasColumnType("integer");

                    b.Property<int>("PlayedRounds")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.HasIndex("SeasonId", "UserId")
                        .IsUnique();

                    b.ToTable("Standings");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CrestUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("Division")
                        .HasColumnType("integer");

                    b.Property<string>("FifaCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsBigSevenClub")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("TeamType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Club");

                    b.Property<int>("WorldCupTitles")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 0,
                            IsBigSevenClub = true,
                            Name = "Arsenal",
                            ShortName = "ARS",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 0,
                            IsBigSevenClub = true,
                            Name = "Chelsea",
                            ShortName = "CHE",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 0,
                            IsBigSevenClub = true,
                            Name = "Liverpool",
                            ShortName = "LIV",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 0,
                            IsBigSevenClub = true,
                            Name = "Manchester City",
                            ShortName = "MCI",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 0,
                            IsBigSevenClub = true,
                            Name = "Manchester United",
                            ShortName = "MUN",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 0,
                            IsBigSevenClub = true,
                            Name = "Newcastle",
                            ShortName = "NEW",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111107"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 0,
                            IsBigSevenClub = true,
                            Name = "Tottenham",
                            ShortName = "TOT",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("245363b3-ca70-a57a-95d5-570b2ecd5f6a"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 0,
                            IsBigSevenClub = false,
                            Name = "Aston Villa",
                            ShortName = "AVL",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("c96f7062-79e3-928c-8ec2-f70182a33e27"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 0,
                            IsBigSevenClub = false,
                            Name = "Bournemouth",
                            ShortName = "BOU",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("71c8f089-3ede-ab7b-7f4c-ba436a85ee96"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 0,
                            IsBigSevenClub = false,
                            Name = "Brentford",
                            ShortName = "BRE",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("87e33b81-1032-b701-e270-fbf4a0a5e4fa"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 0,
                            IsBigSevenClub = false,
                            Name = "Brighton & Hove Albion",
                            ShortName = "BHA",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("e8a096f2-7f6b-7a4f-8d39-69489afb69d9"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 0,
                            IsBigSevenClub = false,
                            Name = "Burnley",
                            ShortName = "BUR",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("332721ec-239e-3a52-743b-f9a10e4ffc74"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 0,
                            IsBigSevenClub = false,
                            Name = "Crystal Palace",
                            ShortName = "CRY",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("ef9f35f5-5195-1954-e356-14d89b4dfad9"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 0,
                            IsBigSevenClub = false,
                            Name = "Everton",
                            ShortName = "EVE",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("8608c4c3-d9ea-d5af-d80b-7a64f7e7084a"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 0,
                            IsBigSevenClub = false,
                            Name = "Fulham",
                            ShortName = "FUL",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("f616d444-c35d-1e44-65c7-ce9ae64f734a"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 0,
                            IsBigSevenClub = false,
                            Name = "Leeds United",
                            ShortName = "LEE",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("639ccdd4-40ed-f52d-f80e-7aa0f0d399dd"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 0,
                            IsBigSevenClub = false,
                            Name = "Nottingham Forest",
                            ShortName = "NFO",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("b9627c9c-b4dc-2906-cfff-9a1b67fe7872"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 0,
                            IsBigSevenClub = false,
                            Name = "Sunderland",
                            ShortName = "SUN",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("464c232d-1caa-774c-1477-6ca9c2991738"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 0,
                            IsBigSevenClub = false,
                            Name = "West Ham United",
                            ShortName = "WHU",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("1a6265b5-9b03-67cf-914d-3d09f651c999"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 0,
                            IsBigSevenClub = false,
                            Name = "Wolverhampton Wanderers",
                            ShortName = "WOL",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("f77c1d3f-d3c5-118f-1a0a-bab078be9695"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Birmingham City",
                            ShortName = "BIR",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("571d2691-c2e5-ad91-0441-e921d97e1e51"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Blackburn Rovers",
                            ShortName = "BLB",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("962ce353-613c-74db-83d5-cca35bede489"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Bristol City",
                            ShortName = "BRC",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("3b2c5fa1-a85c-649c-3fc0-e190fd0a663b"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Charlton Athletic",
                            ShortName = "CHA",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("e81bf932-8829-70a6-e530-fdf18e26adf9"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Coventry City",
                            ShortName = "COV",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("c4cb6ae6-7dc8-efcd-ceb5-2b68e6919110"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Derby County",
                            ShortName = "DER",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("c77966c8-92ed-c0fa-396e-475f5da6bd88"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Hull City",
                            ShortName = "HUL",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("197657bf-8de2-f68a-f5c4-e69ed9919c03"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Ipswich Town",
                            ShortName = "IPS",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("f29f0509-a891-a240-ed5e-b635b29130bd"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Leicester City",
                            ShortName = "LEI",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("18337fcd-e014-bbc2-40ba-9e1d5b7d7e4a"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Middlesbrough",
                            ShortName = "MID",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("9cd2ed8d-098a-b2cb-dcde-d100b88dd3dd"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Millwall",
                            ShortName = "MIL",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("be4ff455-5e31-dc6c-4cf7-e87c01d4062b"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Norwich City",
                            ShortName = "NOR",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("79e62f46-f73d-82a8-a7ee-d974bd26b2e6"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Oxford United",
                            ShortName = "OXF",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("3e90654b-a2fb-5504-8f97-41fd1fe4f2f1"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Portsmouth",
                            ShortName = "POR",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("412d6c85-7d1f-e91b-db73-224aa5c6feff"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Preston North End",
                            ShortName = "PNE",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("689e63d3-59cc-e1c3-9060-65e1663b8501"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Queens Park Rangers",
                            ShortName = "QPR",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("372d2f0b-0d74-5d16-c6e8-4d0c88ee5d30"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Sheffield United",
                            ShortName = "SHU",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("452dce33-d510-05e9-9d4c-009b3b524689"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Sheffield Wednesday",
                            ShortName = "SHW",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("9d17cb18-c8d3-c5c7-fe4c-3990d0dc1d6c"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Southampton",
                            ShortName = "SOU",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("0643d237-1236-a614-6deb-5c1d50489d65"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Stoke City",
                            ShortName = "STK",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("38147db7-f93e-19b4-0a99-b6fc1e79a285"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Swansea City",
                            ShortName = "SWA",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("f94609eb-94f8-c0ef-ca27-9935d5ce875f"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Watford",
                            ShortName = "WAT",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("eabbc77e-85be-2bb6-40c2-c4f647ac984f"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "West Bromwich Albion",
                            ShortName = "WBA",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("633f620c-6d3a-18d1-e042-049ce9648fcc"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 2,
                            IsBigSevenClub = false,
                            Name = "Wrexham",
                            ShortName = "WRE",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("52aa8de5-bb71-7819-e9e3-9e721ae9fbb1"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "AFC Wimbledon",
                            ShortName = "WIM",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("5d33ab69-d162-b60b-2edc-dc3dbd731177"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Barnsley",
                            ShortName = "BAR",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("0b6ec555-86c4-3619-684d-f6e985eb6dab"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Blackpool",
                            ShortName = "BLA",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("527eb8ae-87e3-4dcd-edcf-1fdc272d065d"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Bolton Wanderers",
                            ShortName = "BOL",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("a606681b-46b1-9faf-919d-a93a8b2e6fd3"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Bradford City",
                            ShortName = "BRA",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("8bacfc2c-633e-4eff-bbaa-d233916b8763"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Burton Albion",
                            ShortName = "BTN",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("a4787bdf-b277-7fde-f8f1-1d2ce6babf6a"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Cardiff City",
                            ShortName = "CAR",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("b1601569-da6c-a45a-f72d-0a0a801132cc"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Doncaster Rovers",
                            ShortName = "DON",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("309f8718-aefc-5b6d-87c4-873e92e05832"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Exeter City",
                            ShortName = "EXE",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("b42c38ba-d9f9-6898-5c95-0572b8cc4461"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Huddersfield Town",
                            ShortName = "HUD",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("157207da-1d38-a621-7402-9bd9c6e0e1ba"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Leyton Orient",
                            ShortName = "LEY",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("0c0d8b61-57be-7e2e-0f32-160c4fb6c6e8"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Lincoln City",
                            ShortName = "LIN",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("b6083d70-d7bb-fc50-453f-e77883d22d15"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Luton Town",
                            ShortName = "LUT",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("3324f7f9-7477-4814-9292-4f5498afc2ca"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Mansfield Town",
                            ShortName = "MNF",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("a4a9a1a8-a7ee-047e-1753-d0ac5a1288fd"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Northampton Town",
                            ShortName = "NTH",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("ce8d4549-4834-494e-3d49-daf0e180e35e"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Peterborough United",
                            ShortName = "PET",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("76c73df3-4551-4881-f3f6-a40dc4f0ab36"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Plymouth Argyle",
                            ShortName = "PLY",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("94ce7ba0-e73b-79ec-619d-c0817e296bb6"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Port Vale",
                            ShortName = "PVL",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("b4b1c616-ac3a-da52-8f53-3925ce003bf0"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Reading",
                            ShortName = "REA",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("a87325bb-8d0c-d832-fbf2-f6eb99c6d78f"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Rotherham United",
                            ShortName = "ROT",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("e226a779-586d-75f6-8704-4b06e8053001"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Stevenage",
                            ShortName = "STV",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("412df6cd-a237-a841-56e8-d5aa14d69283"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Stockport County",
                            ShortName = "STO",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("619881df-c28b-a91f-6bb6-9fbc9533545c"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Wigan Athletic",
                            ShortName = "WIG",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("7a93656f-2b11-497d-51e3-92762e8cca96"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Division = 3,
                            IsBigSevenClub = false,
                            Name = "Wycombe Wanderers",
                            ShortName = "WYC",
                            TeamType = "Club",
                            WorldCupTitles = 0
                        },
                        new
                        {
                            Id = new Guid("71f27b42-ab7c-4737-09e8-bb01652183ce"),
                            CountryCode = "BR",
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FifaCode = "BRA",
                            IsBigSevenClub = false,
                            Name = "Brazil",
                            ShortName = "BRA",
                            TeamType = "NationalTeam",
                            WorldCupTitles = 5
                        },
                        new
                        {
                            Id = new Guid("52301cce-5863-636d-318d-b27ebfa25024"),
                            CountryCode = "DE",
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FifaCode = "GER",
                            IsBigSevenClub = false,
                            Name = "Germany",
                            ShortName = "GER",
                            TeamType = "NationalTeam",
                            WorldCupTitles = 4
                        },
                        new
                        {
                            Id = new Guid("9545115a-c6f2-0dd4-d348-382368a54f06"),
                            CountryCode = "AR",
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FifaCode = "ARG",
                            IsBigSevenClub = false,
                            Name = "Argentina",
                            ShortName = "ARG",
                            TeamType = "NationalTeam",
                            WorldCupTitles = 3
                        },
                        new
                        {
                            Id = new Guid("ae6e37b7-826b-a375-35d3-d0b34195180b"),
                            CountryCode = "FR",
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FifaCode = "FRA",
                            IsBigSevenClub = false,
                            Name = "France",
                            ShortName = "FRA",
                            TeamType = "NationalTeam",
                            WorldCupTitles = 2
                        },
                        new
                        {
                            Id = new Guid("d5ff7176-17c0-25aa-7376-711eacfd3658"),
                            CountryCode = "UY",
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FifaCode = "URU",
                            IsBigSevenClub = false,
                            Name = "Uruguay",
                            ShortName = "URU",
                            TeamType = "NationalTeam",
                            WorldCupTitles = 2
                        },
                        new
                        {
                            Id = new Guid("d2d20443-0dc4-f5d3-e018-519cc8e64172"),
                            CountryCode = "ES",
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FifaCode = "ESP",
                            IsBigSevenClub = false,
                            Name = "Spain",
                            ShortName = "ESP",
                            TeamType = "NationalTeam",
                            WorldCupTitles = 1
                        },
                        new
                        {
                            Id = new Guid("b45e5449-8c83-673e-e468-68bb04f633f2"),
                            CountryCode = "GB",
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FifaCode = "ENG",
                            IsBigSevenClub = false,
                            Name = "England",
                            ShortName = "ENG",
                            TeamType = "NationalTeam",
                            WorldCupTitles = 1
                        });
                });

            modelBuilder.Entity("Palpitao.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RejectedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("Approved");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@palpitao.local",
                            IsActive = true,
                            Name = "Administrador",
                            PasswordHash = "$2a$11$rqqFHI1KeD4V96P8cdiPBeR8U8MEQEwED.AbOQ2aeuQeAeNJN3U.m",
                            Role = "Admin",
                            Status = "Approved"
                        });
                });

            modelBuilder.Entity("Palpitao.Api.Entities.Absence", b =>
                {
                    b.HasOne("Palpitao.Api.Entities.Round", "Round")
                        .WithMany("Absences")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palpitao.Api.Entities.User", "User")
                        .WithMany("Absences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Round");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.AbsenceOverride", b =>
                {
                    b.HasOne("Palpitao.Api.Entities.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palpitao.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Round");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.AuditLog", b =>
                {
                    b.HasOne("Palpitao.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.GroupUser", b =>
                {
                    b.HasOne("Palpitao.Api.Entities.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palpitao.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.OcrImportBatch", b =>
                {
                    b.HasOne("Palpitao.Api.Entities.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.OcrPredictionCandidate", b =>
                {
                    b.HasOne("Palpitao.Api.Entities.OcrImportBatch", "Batch")
                        .WithMany("Candidates")
                        .HasForeignKey("OcrImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.Prediction", b =>
                {
                    b.HasOne("Palpitao.Api.Entities.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Palpitao.Api.Entities.RoundMatch", "RoundMatch")
                        .WithMany("Predictions")
                        .HasForeignKey("RoundMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palpitao.Api.Entities.User", "User")
                        .WithMany("Predictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Round");

                    b.Navigation("RoundMatch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.PredictionScore", b =>
                {
                    b.HasOne("Palpitao.Api.Entities.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palpitao.Api.Entities.RoundMatch", "RoundMatch")
                        .WithMany()
                        .HasForeignKey("RoundMatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Palpitao.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Round");

                    b.Navigation("RoundMatch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.Round", b =>
                {
                    b.HasOne("Palpitao.Api.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Palpitao.Api.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Palpitao.Api.Entities.Season", "Season")
                        .WithMany("Rounds")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Group");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.RoundMatch", b =>
                {
                    b.HasOne("Palpitao.Api.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Palpitao.Api.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Palpitao.Api.Entities.Round", "Round")
                        .WithMany("Matches")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.RoundParticipantResult", b =>
                {
                    b.HasOne("Palpitao.Api.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Palpitao.Api.Entities.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palpitao.Api.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palpitao.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Round");

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.Season", b =>
                {
                    b.HasOne("Palpitao.Api.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.Standing", b =>
                {
                    b.HasOne("Palpitao.Api.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Palpitao.Api.Entities.Season", "Season")
                        .WithMany("Standings")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palpitao.Api.Entities.User", "User")
                        .WithMany("Standings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.Group", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.OcrImportBatch", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.Round", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.RoundMatch", b =>
                {
                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.Season", b =>
                {
                    b.Navigation("Rounds");

                    b.Navigation("Standings");
                });

            modelBuilder.Entity("Palpitao.Api.Entities.User", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Predictions");

                    b.Navigation("Standings");
                });
#pragma warning restore 612, 618
        }
    }
}
