// @ts-check
const eslint = require('@eslint/js');
const { defineConfig } = require('eslint/config');
const tseslint = require('typescript-eslint');
const angular = require('angular-eslint');

// Layer boundaries (the frontend twin of the backend's architecture tests). Flat config replaces a
// rule's options per block, so every block lists the patterns that apply to it.
const noDeepRelative = {
  regex: /^(\.\.\/){2,}/.source,
  message: 'Climb at most one level: import through @core, @shared, @env or @version.',
};
const noFeatureOrLayout = {
  regex: /(^|\/)(features|layout)\//.source,
  message: 'core/ and shared/ are below the features and the layout: they must not import them.',
};
const restrictImports = (...patterns) => ({ 'no-restricted-imports': ['error', { patterns }] });

module.exports = defineConfig([
  {
    // src/version.ts is generated by scripts/generate-version.mjs on every build.
    ignores: ['src/version.ts'],
  },
  {
    files: ['**/*.ts'],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommended,
      tseslint.configs.stylistic,
      angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    rules: {
      '@angular-eslint/directive-selector': [
        'error',
        {
          type: 'attribute',
          prefix: 'app',
          style: 'camelCase',
        },
      ],
      '@angular-eslint/component-selector': [
        'error',
        {
          type: 'element',
          prefix: 'app',
          style: 'kebab-case',
        },
      ],
      // Allow intentionally-unused bindings/args named with a leading underscore.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // Empty arrow callbacks are a deliberate "ignore result" idiom (e.g. fire-and-forget).
      '@typescript-eslint/no-empty-function': ['error', { allow: ['arrowFunctions'] }],
    },
  },
  {
    files: ['src/**/*.ts'],
    rules: restrictImports(noDeepRelative),
  },
  {
    files: ['src/app/core/**/*.ts'],
    rules: restrictImports(noDeepRelative, noFeatureOrLayout, {
      regex: /^@shared\//.source,
      message: 'core/ is the bottom layer: shared/ builds on it, not the other way round.',
    }),
  },
  {
    files: ['src/app/shared/**/*.ts'],
    rules: restrictImports(noDeepRelative, noFeatureOrLayout),
  },
  {
    // A feature's own files never reach into a sibling feature; anything two features need
    // belongs in @shared or @core.
    files: ['src/app/features/*/*.ts'],
    rules: restrictImports(noDeepRelative, {
      regex: /^\.\.\//.source,
      message: 'Features do not import each other: share it through @shared or @core.',
    }),
  },
  {
    files: ['**/*.html'],
    extends: [angular.configs.templateRecommended, angular.configs.templateAccessibility],
    rules: {
      // Surfaced as a warning (ratchet): several Bootstrap forms use a sibling
      // <label> without a for/id link. Tracked for incremental a11y cleanup so the
      // lint gate stays green while the backlog is worked down.
      '@angular-eslint/template/label-has-associated-control': 'warn',
    },
  },
]);
