// Stamps the build version into src/version.ts (gitignored). Runs automatically
// before start/build/test/watch via npm pre-hooks. The version comes from the latest
// git tag (set by semantic-release, e.g. v1.2.0); on an exact tag it shows that
// version, otherwise the most recent release tag. Falls back to package.json when
// there are no tags / no git (e.g. a source export). Commit + build time are extras.
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(join(here, '..', 'package.json'), 'utf8'));

function git(cmd, fallback) {
  try {
    return execSync(cmd, { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
  } catch {
    return fallback;
  }
}

const tag = git('git describe --tags --abbrev=0', '');
const version = (tag || `v${pkg.version}`).replace(/^v/, '');
const commit = git('git rev-parse --short HEAD', 'unknown');

const content = `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit, do not commit.
export const APP_VERSION: string = '${version}';
export const APP_COMMIT: string = '${commit}';
export const APP_BUILD_TIME: string = '${new Date().toISOString()}';
`;

writeFileSync(join(here, '..', 'src', 'version.ts'), content);
console.log(`Generated src/version.ts -> v${version} (${commit})`);
