// Stamps the build version into src/version.ts (gitignored). Runs automatically
// before start/build/test/watch via npm pre-hooks. Version comes from package.json
// (bump it with `npm version <x.y.z>`, which also creates the v<x.y.z> deploy tag);
// the short git commit and build time are best-effort extras.
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(join(here, '..', 'package.json'), 'utf8'));

let commit = 'unknown';
try {
  commit = execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
    .toString()
    .trim();
} catch {
  // Not a git checkout (e.g. a source export) — keep the fallback.
}

const content = `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit, do not commit.
export const APP_VERSION: string = '${pkg.version}';
export const APP_COMMIT: string = '${commit}';
export const APP_BUILD_TIME: string = '${new Date().toISOString()}';
`;

writeFileSync(join(here, '..', 'src', 'version.ts'), content);
console.log(`Generated src/version.ts -> v${pkg.version} (${commit})`);
